---
# tasks file for hmpps-delius-core-pwm-bootstrap
- name: Setup config directory
  file:
    path: '{{ config_location }}'
    state: directory
    owner: 1234

- name: Generate the config file
  template:
    src: PwmConfiguration.xml.j2
    dest: '{{ config_location }}/PwmConfiguration.xml'
    owner: 1234